# Generated by Django 5.2.5 on 2025-10-10 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to='img_empresa', verbose_name='Logo de la Empresa')),
                ('name_company', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('phone_company', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('nit', models.IntegerField(blank=True, null=True, verbose_name='NIT')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre del servicio')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'last_name'), name='unique_client_name_lastname')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('img_background', models.ImageField(blank=True, null=True, upload_to='img_productos', verbose_name='Imagen Fondo')),
                ('img_name', models.ImageField(blank=True, null=True, upload_to='img_productos_name', verbose_name='Imagen Nombre')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='administrador.category')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.IntegerField(verbose_name='Ficha')),
                ('img_machine', models.ImageField(blank=True, null=True, upload_to='img_maquinas', verbose_name='Imagen de Evidencia de la Máquina')),
                ('brand', models.CharField(blank=True, choices=[('EPSON', 'EPSON'), ('brother', 'brother'), ('APPLE', 'APPLE'), ('LENOVO', 'LENOVO'), ('DELL', 'DELL'), ('HP', 'HP'), ('ASUS', 'ASUS'), ('ACER', 'ACER'), ('MICROSOFT', 'MICROSOFT'), ('SAMSUNG', 'SAMSUNG'), ('MSI', 'MSI'), ('TOSHIBA', 'TOSHIBA'), ('HUAWEI', 'HUAWEI'), ('SONY', 'SONY'), ('OTHER', 'Otra (escribir)')], max_length=100, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalle')),
                ('problem', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('diagnostic', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Posición')),
                ('accessories', models.TextField(blank=True, null=True, verbose_name='Accesorios')),
                ('status', models.CharField(choices=[('Reparación', 'Reparación'), ('Cancelado', 'Cancelado'), ('Por Entregar', 'Por Entregar'), ('Entregado', 'Entregado')], default='Recibido', max_length=50, null=True, verbose_name='Estado')),
                ('price_aprox', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('price_extra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Extra')),
                ('price_descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento')),
                ('price_fact', models.BooleanField(default=True, verbose_name='¿Incluir IVA?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo')),
                ('devolucion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Devolución')),
                ('price_a_cuenta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio a Cuenta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de Recepción')),
                ('delivery_in', models.DateTimeField(blank=True, null=True, verbose_name='fecha de Entrega')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='administrador.client')),
                ('services', models.ManyToManyField(blank=True, related_name='machines', to='administrador.service')),
            ],
        ),
    ]
